Rewrite without dolittle
RaaLabs/Connectors.NMEA pull request #12
Opened 2021-04-12 22:01 UTC by srudaa

Rewrite and rename the NMEA connector based on new framework (https://github.com/RaaLabs/Edge).

2021-04-13 16:37 UTC, thotokraa requested changes

2021-04-13 16:37 UTC, thotokraa commented on Specifications/Drivers/EventParsedInstanceFactory.cs
> +            var eventParsed = new events.EventParsed
This expression can possibly be replaced with the following code:
```csharp
var eventParsed = row.CreateInstance<events.EventParsed>();
```

2021-04-13 16:37 UTC, thotokraa commented on Specifications/Drivers/IEventInstanceFactory.cs
> +    interface IEventInstanceFactory<T>
This interface is part of `RaaLabs.Edge.Testing` from version 1.1.0.

2021-04-13 16:37 UTC, thotokraa commented on Specifications/Drivers/IProducedEventVerifier.cs
> +    interface IProducedEventVerifier<T>
This interface is part of `RaaLabs.Edge.Testing` from version 1.1.0.

2021-04-13 16:37 UTC, thotokraa commented on Specifications/Drivers/TypeMapper.cs
> +    public class TypeMapping : Dictionary<string, Type>
This class is part of `RaaLabs.Edge.Testing` from version 1.1.0. It should be replaced with a hook for injecting the type mappings into that class, as instructed in the readme file for the testing library.

2021-04-13 16:37 UTC, thotokraa commented on Specifications/Features/SentenceParser.feature
> +        Then the exception "UnsupportedSentenceException" is thrown with message "Talker 'AA' with identifier 'AAA' is not supported in sentence '$AAAAA,5.2,0.0,10.0*63'"
In my opinion, testing the string content of an exception is not the best way to test the outcome from a test, although it is very convenient. We could discuss this a bit further before merging.

2021-04-13 16:37 UTC, thotokraa commented on Specifications/Features/StateHandler.feature
> +        Then the following events of type NMEADatapointOutput is produced
As the testing framework works right now, we don't test that the number of events produced is exactly equal to the number of rows in this table, which means that this test would probably pass even if you passed HEVHW before HEHDT. This needs to be fixed in the Testing library.

2021-04-13 16:37 UTC, thotokraa commented on Specifications/Features/StateHandler.feature
> +            | NMEA   | HeadingTrue | 5.0   | 1617915312000 |
Could you add some tests for what should happen to incoming data points when the current data points are stale (produced more than 60 seconds ago)?

2021-04-13 16:37 UTC, thotokraa commented on Specifications/Hooks/InstanceFactoryProvider.cs
> +    class InstanceFactoryProvider
This class is not needed if you use `RaaLabs.Edge.Testing` v1.1.0.

2021-04-13 16:37 UTC, thotokraa commented on Specifications/Hooks/LoggerProvider.cs
> +    public sealed class LoggerProvider
This class is not needed if you use `RaaLabs.Edge.Testing`.

2021-04-13 16:37 UTC, thotokraa commented on Specifications/Hooks/SentenceParserProvider.cs
> +            //var registerFunction = GetType().GetMethod("RegisterSentenceFormat");
Can we remove these lines now?

2021-04-13 16:37 UTC, thotokraa commented on Specifications/Steps/HandlerSteps.cs
> +    public sealed class HandlerSteps
This class is now provided in the `RaaLabs.Edge.Testing` library.

2021-04-13 16:37 UTC, thotokraa commented on Specifications/specflow.json
> +    "allowDebugGeneratedFiles": true
To use `RaaLabs.Edge.Testing`, you also need to add `stepAssemblies` field to this file, as specified in the testing framework readme.

2021-04-13 18:58 UTC, srudaa commented on Source/Connector.cs
> +                    .WaitAndRetryForeverAsync(retryAttempt => TimeSpan.FromSeconds(Math.Pow(2, retryAttempt)),
Should we?

2021-04-13 19:13 UTC, srudaa commented on Source/Connector.cs
> +                        var sentence = reader.Current;
I did not get this to work. However, if it times out the socket will close and a new reader will be defined?

2021-04-14 11:29 UTC, srudaa commented on Specifications/Features/StateHandler.feature
> +        Then the following events of type NMEADatapointOutput is produced
Fixed in testing library v1.1.1

2021-04-14 13:34 UTC, srudaa commented on Specifications/Drivers/EventParsedInstanceFactory.cs
> +            var eventParsed = new events.EventParsed
Did not work. Got a lot of errors regarding floats. Will keep it as it is.

2021-04-16 06:50 UTC, srudaa commented
@thotokraa could you have another look. I have pushed fixes based on your awesome feedback.

2021-04-19 09:20 UTC, thotokraa requested changes
Please fix the last code smell before merging.

2021-04-19 09:20 UTC, thotokraa commented on Source/NMEAStreamReader.cs
> +    public class NMEAStreamReader
Add `static` here.

2021-04-19 10:59 UTC, thotokraa approved these changes

2021-04-19 11:11 UTC, merged