Trying to push latest tag
RaaLabs/Connectors.NMEA pull request #23
Opened 2021-06-15 20:45 UTC by rafaelschlatter

## Summary

Push latest tag. Labelling this PR with "patch" to get a test run of the github action.

### Changed

- Adapted github action to tag image with latest and push it to the acr each time a regular version is pushed.

2021-06-15 21:00 UTC, srudaa requested changes
Should not remove docker build for regular push.

2021-06-15 21:00 UTC, srudaa commented on .github/workflows/dotnet.yml
> -
We should check if the container builds before we merge. So I think we should keep this. If you don't won't to build two times during merge this can be added. 

```shell
      if: ${{ steps.context.outputs.should-publish == 'false' 
```

2021-06-16 06:20 UTC, rafaelschlatter commented on .github/workflows/dotnet.yml
> -
Good idea, thanks!

2021-06-16 06:24 UTC, srudaa approved these changes

2021-06-16 06:25 UTC, merged