V7.0.0 rc
RaaLabs/Connectors.NMEA pull request #49
Opened 2022-11-10 23:43 UTC by srudaa

## Summary

Summary of the PR here. The GitHub release description is created from this comment so keep it nice and descriptive.

Remember to remove sections that you don't need or use.

### Added

- Restart the connector if no data is received for 60 seconds. The connector will also try to ping the source and report the results. 
- Parser for Rudder Sensor Angle.
- Sample the NMEA state if it is present, will also log when the status changes for each tag.
- Able to report when non-ASCII characters are received. 

### Changed

- When only non-prioritised sentences are received the connector will lock onto the first it sees until restart.
- Parsing is done by a static class
- Renamed StateHandler to ParsedEventHandler
- Moved to logic from ParsedEventHandler to StateProcessor 
- VBW will output GroundSpeed instead of SpeedOverGround

### Fixed

- Able to handle NMEA sentences if it contains non-NMEA sentences in the same TCP string line. 
- Improved logging 

### Removed

- Stacktrace in logs where the exception is known. 

### Deprecated

- Stream all sentences if they are no priorities.

2022-11-11 15:16 UTC, thotokraa requested changes
Good job. I want some changes before I approve, though, especially the `Thread.Sleep(...)` call.

2022-11-11 15:16 UTC, thotokraa commented on Specifications/Features/NMEALineHandlerNonNMEA.feature
> +      | StringLine               |
Wrong formatting

2022-11-15 16:51 UTC, thotokraa requested changes
Getting there, I just discovered one new data race bug that should be fixed before I approve.

2022-11-15 16:51 UTC, thotokraa commented on Source/RestartModule.cs
> +    private DateTimeOffset _lastTimestampReceived;
According to the [Microsoft documentation](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/variables#96-atomicity-of-variable-references), only references and primitives up to 32 bits are guaranteed to be atomic, meaning that we can be sure that the entire value is written uninterrupted.

The problem with structs is that the thread can be interrupted in the middle of an assignment (as is done on line 40 below), which means that in small time periods, it can contain rubbish data. This isn't a problem with classes, because they are assigned by reference, not by copying the contained data, and because of that, it is atomic.

Unfortunately for us, `DateTimeOffset` is a struct, and not a class. Because of this, we could end up experiencing unexplainable restarts once in a blue moon, because of my explaination above. Fortunately, however, the fix should be quite simple: adding `ref` to this variable declaration: `private ref DateTimeOffset _lastTimestampReceived`. By doing this, we are treating the DateTimeOffset as a class, rather than a struct.

2022-11-15 17:50 UTC, srudaa commented on Source/RestartModule.cs
> +    private DateTimeOffset _lastTimestampReceived;
Thank you. Good spotted. I see that the `ref` is a preview feature?

2022-11-15 19:19 UTC, thotokraa approved these changes

2022-11-16 10:02 UTC, merged